services:
  - type: web
    name: portfolio-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://your-frontend-url.vercel.app
    healthCheckPath: /api/projects
    autoDeploy: true
    branch: master
